apiVersion: v1
kind: Service
metadata:
  name: static-website-service
  namespace: static-website
spec:
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort